#!/bin/bash -xe

cd ${0%*/*}

if [ ! -e Dockerfile ]; then
	echo "ERROR: Dockerfile is missing."
	exit 1
fi

if ! (which docker > /dev/null 2>&1); then
	echo "docker is required to build BFB"
	exit 1
fi

DISTRO="mariner"
DISTRO_VERSION="2.0"
BOOTIMAGES_VERSION="4.0.3"

# wget -P . --quiet -r --no-verbose --no-directories -l1 --no-parent -A '*.aarch64.rpm' -R "index.html*" https://linux.mellanox.com/public/repo/bluefield/${BOOTIMAGES_VERSION}/bootimages/prod/
wget -P . --quiet -r --no-verbose --no-directories -l1 --no-parent -R "index.html" -A 'hook-bootkit' http://192.168.1.28:8888
# wget -P . --quiet -r --no-verbose --no-directories -l1 --no-parent -R "index.html" -A 'mlnx-ofa_kernel-23.04-3.cm2.aarch64.rpm' http://192.168.1.28:8888/rpms/ofed/RPMS/aarch64/
# wget -P . --quiet -r --no-verbose --no-directories -l1 --no-parent -R "index.html" -A 'kernel-5.15.111.1-1.cm2.aarch64.rpm' http://192.168.1.28:8888/rpms/bluefield/aarch64/
# wget -P . --quiet -r --no-verbose --no-directories -l1 --no-parent -R "index.html" -A 'kernel-devel-5.15.111.1-1.cm2.aarch64.rpm' http://192.168.1.28:8888/rpms/bluefield/aarch64/
# wget -P . --quiet -r --no-verbose --no-directories -l1 --no-parent -R "index.html" -A 'kernel-headers-5.15.111.1-1.cm2.noarch.rpm' http://192.168.1.28:8888/rpms/bluefield/aarch64/

#wget -P . -r --no-verbose --no-directories -l1 --no-parent -R "index.html" -A 'hook-bootkit' http://192.168.1.28:8888
#wget -P . -r --no-verbose --no-directories -l1 --no-parent -R "index.html" -A 'mlnx-ofa_kernel-23.04-3.cm2.aarch64.rpm' http://192.168.1.28:8888/rpms/ofed/RPMS/aarch64/
#wget -P . -r --no-verbose --no-directories -l1 --no-parent -R "index.html" -A 'kernel-5.15.111.1-1.cm2.aarch64.rpm' http://192.168.1.28:8888/rpms/bluefield/aarch64/
#wget -P . -r --no-verbose --no-directories -l1 --no-parent -R "index.html" -A 'kernel-devel-5.15.111.1-1.cm2.aarch64.rpm' http://192.168.1.28:8888/rpms/bluefield/aarch64/

docker rm -f BlueField_OS_${DISTRO}_${DISTRO_VERSION}

docker build --platform linux/arm64 -t bfb_runtime_${DISTRO}${DISTRO_VERSION} -f Dockerfile .
docker run -t --privileged -e container=docker \
	-v $PWD:/workspace \
	--platform linux/arm64 \
	--name BlueField_OS_${DISTRO}_${DISTRO_VERSION} \
	--mount type=bind,source=/dev,target=/dev \
	--mount type=bind,source=/sys,target=/sys \
	--mount type=bind,source=/proc,target=/proc \
	bfb_runtime_${DISTRO}${DISTRO_VERSION}

readlink -f *aarch64.bfb
